openapi: 3.0.0
info:
  title: Payment API
  description: Service for making payments by credit card
  version: 1.0.0
paths:
  /payment:
    get:
      summary: Gets payment by session_id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionId'
            example:
              session_id: ecef274b-c4d9-11ea-9c98-16e54378dfba
      responses:
        '200':    # status code
          description: A payment JSON object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentData'
              example:
                id: 42
                sum: 50000
                purpose: An example payment
                session_id: ecef274b-c4d9-11ea-9c98-16e54378dfba
                completed: false
    post:
      summary: Creates payment and returns session_id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
            example:
              sum: 50000
              purpose: An example payment
      responses:
        '200':    # status code
          description: A payment JSON object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionId'
              example:
                session_id: ecef274b-c4d9-11ea-9c98-16e54378dfba
  /validate:
    post:
      summary: Validates card and makes payment completed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCardData'
            example:
              user: Alex Petrov
              number: "4561261212345467"
              cvv: 765
              expire_date: 03/22
              session_id: ecef274b-c4d9-11ea-9c98-16e54378dfba
      responses:
        '200':    # status code
          description: A payment JSON object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: ""
components:
  schemas:
    SessionId:
      title: session id
      type: object
      properties:
        session_id:
          type: string
          description: a payment session id
      required:
        - session_id
    PaymentData:
      title: a payment
      type: object
      properties:
        id:
          type: integer
        sum:
          type: integer
        purpose:
          type: string
        session_id:
          type: string
        completed:
          type: boolean
    CreatePaymentRequest:
      title: a payment data
      type: object
      properties:
        sum:
          type: integer
        purpose:
          type: string
    CreditCardData:
      title: credit card data
      type: object
      properties:
        user:
          type: string
        number:
          type: string
        cvv:
          type: integer
        expire_date:
          type: string
        session_id:
          type: string
    Error:
      title: error object
      type: object
      properties:
        error:
          type: string
            
    